spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.5"
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 100Mi
